FROM python:3.8-slim-buster

COPY ./model/requirements.txt /
RUN pip install -r requirements.txt

COPY ./lib /lib 
COPY ./data /data
COPY ./scripts/train.py /scripts/

WORKDIR /scripts
CMD [ "python3", "train.py"]